2020-12-26 22:17:02,090 INFO    MainThread:14485 [wandb_setup.py:_flush():70] setting env: {}
2020-12-26 22:17:02,090 INFO    MainThread:14485 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2020-12-26 22:17:02,091 INFO    MainThread:14485 [wandb_setup.py:_flush():70] setting login settings: {}
2020-12-26 22:17:02,091 INFO    MainThread:14485 [wandb_init.py:_log_setup():303] Logging user logs to /Users/shreyasshandilya/Desktop/Shandilya/Padhai/CS6886/assignment7/wandb/run-20201226_221702-conv_naive/logs/debug.log
2020-12-26 22:17:02,091 INFO    MainThread:14485 [wandb_init.py:_log_setup():304] Logging internal logs to /Users/shreyasshandilya/Desktop/Shandilya/Padhai/CS6886/assignment7/wandb/run-20201226_221702-conv_naive/logs/debug-internal.log
2020-12-26 22:17:05,337 INFO    MainThread:14485 [wandb_run.py:_console_start():1237] atexit reg
2020-12-26 22:17:05,395 INFO    MainThread:14485 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.REDIRECT
2020-12-26 22:17:05,395 INFO    MainThread:14485 [wandb_run.py:_redirect():1107] Redirecting console.
2020-12-26 22:17:05,395 INFO    MainThread:14485 [redirect.py:install():204] install start
2020-12-26 22:17:05,396 INFO    MainThread:14485 [redirect.py:install():219] install stop
2020-12-26 22:17:05,396 INFO    MainThread:14485 [redirect.py:install():204] install start
2020-12-26 22:17:05,396 INFO    MainThread:14485 [redirect.py:install():219] install stop
2020-12-26 22:17:05,397 INFO    MainThread:14485 [wandb_run.py:_redirect():1151] Redirects installed.
2020-12-26 22:17:05,438 INFO    MainThread:14485 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2020-12-26 22:17:05,439 INFO    MainThread:14485 [wandb_run.py:_restore():1179] restore
2020-12-26 22:17:05,439 INFO    MainThread:14485 [redirect.py:uninstall():223] uninstall start
2020-12-26 22:17:05,440 INFO    MainThread:14485 [redirect.py:_stop():278] _stop: stdout
2020-12-26 22:17:05,440 INFO    MainThread:14485 [redirect.py:_stop():284] _stop closed: stdout
2020-12-26 22:17:05,440 INFO    stdout    :14485 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2020-12-26 22:17:05,441 INFO    stdout    :14485 [redirect.py:_pipe_relay():136] relay done done: stdout
2020-12-26 22:17:05,441 INFO    MainThread:14485 [redirect.py:_stop():290] _stop joined: stdout
2020-12-26 22:17:05,441 INFO    MainThread:14485 [redirect.py:_stop():292] _stop rd closed: stdout
2020-12-26 22:17:05,441 INFO    MainThread:14485 [redirect.py:uninstall():227] uninstall done
2020-12-26 22:17:05,441 INFO    MainThread:14485 [redirect.py:uninstall():223] uninstall start
2020-12-26 22:17:05,441 INFO    MainThread:14485 [redirect.py:_stop():278] _stop: stderr
2020-12-26 22:17:05,441 INFO    MainThread:14485 [redirect.py:_stop():284] _stop closed: stderr
2020-12-26 22:17:05,441 INFO    stderr    :14485 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2020-12-26 22:17:05,442 INFO    stderr    :14485 [redirect.py:_pipe_relay():136] relay done done: stderr
2020-12-26 22:17:05,442 INFO    MainThread:14485 [redirect.py:_stop():290] _stop joined: stderr
2020-12-26 22:17:05,442 INFO    MainThread:14485 [redirect.py:_stop():292] _stop rd closed: stderr
2020-12-26 22:17:05,442 INFO    MainThread:14485 [redirect.py:uninstall():227] uninstall done
2020-12-26 22:17:05,743 INFO    MainThread:14485 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "28c31bbc365e4f7980e0461c295707e9"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      total_bytes: 896
    }
  }
}

2020-12-26 22:17:07,748 INFO    MainThread:14485 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "7dd981e2721446f8b2898d0714534db1"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 3001
      total_bytes: 3001
    }
  }
}

2020-12-26 22:17:08,864 INFO    MainThread:14485 [wandb_run.py:_show_files():1536] logging synced files
2020-12-26 22:17:08,867 INFO    MainThread:14485 [internal.py:handle_exit():138] Internal process exited
